{% set name = "pyzbar" %}
{% set version = "0.1.8" %}

package:
  name: "{{ name }}"
  version: "{{ version }}"

source:
  - folder: dist
    url: https://github.com/NaturalHistoryMuseum/{{ name }}/archive/v{{ version }}.tar.gz
    sha256: f51c82c2864f8e5a8d44f55853e027f8cbc592324b7afffa62100f2f9c54cbdb
  - folder: src
    url: https://github.com/NaturalHistoryMuseum/pyzbar/archive/refs/tags/v{{ version }}.tar.gz
    sha256: f51c82c2864f8e5a8d44f55853e027f8cbc592324b7afffa62100f2f9c54cbdb

build:
  number: 1
  script: cd dist && {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - read_zbar = pyzbar.scripts.read_zbar:main

requirements:
  host:
    - python ==2.7.*|>=3.6
    - pip
  run:
    - python ==2.7.*|>=3.6
    - zbar

test:
  source_files:
    - src/pyzbar/tests
  requires:
    - pip
    - numpy >=1.8.2
    - pillow >=3.2.0
    - nose
    - coverage
  imports:
    - pyzbar
  commands:
    - pip check
    - read_zbar --help
    - cd src/pyzbar
    - nosetests --with-coverage --cover-package pyzbar --cover-min-percentage 98

about:
  home: https://github.com/NaturalHistoryMuseum/pyzbar
  license: MIT
  license_family: MIT
  license_file: dist/LICENSE.txt
  summary: Read one-dimensional barcodes and QR codes from Python 2 and 3 using the zbar library.
  doc_url: https://github.com/NaturalHistoryMuseum/pyzbar
  dev_url: https://github.com/NaturalHistoryMuseum/pyzbar

extra:
  recipe-maintainers:
    - Ryan-Dmello
    - bollwyvl
